name: Secretlint
on: [push, pull_request]
env:
  CI: true
jobs:
  secretlint:
    name: "Secretlint"
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_ACCESS_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      - name: lint with secretlint on docker
        run: |
           docker run -v `pwd`:`pwd` \
             -w `pwd` \
             --rm \
             secretlint/secretlint secretlint \
             --secretlintrc .github/workflows/.secretlintrc.json \
             --secretlintignore .github/workflows/.secretlintignore \
             "**/*"
